[tool.poetry]
name = "machine-learning"
version = "0.1.0"
description = ""
authors = ["Dombrovan Mykhailo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.26.4"
pandas = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
